In [1]:
#import dependencies
import pandas as pd
import nltk
from sklearn.metrics import accuracy_score, classification_report

In [2]:
#connect vader
nltk.download("vader_lexicon")

[nltk_data] Downloading package vader_lexicon to
[nltk_data]     C:\Users\Christina\AppData\Roaming\nltk_data...
[nltk_data]   Package vader_lexicon is already up-to-date!

True

In [3]:
#import SentimentIntensityAnalyzer
from nltk.sentiment.vader import SentimentIntensityAnalyzer
sent_analyzer = SentimentIntensityAnalyzer()

In [4]:
#read in data
data = pd.read_csv('0819_UkraineCombinedTweetsDeduped.csv')

In [5]:
data.head()

,Unnamed: 0,userid,username,acctdesc,location,following,followers,totaltweets,usercreatedts,tweetid,...,original_tweet_userid,original_tweet_username,in_reply_to_status_id,in_reply_to_user_id,in_reply_to_screen_name,is_quote_status,quoted_status_id,quoted_status_userid,quoted_status_username,extractedts
0,0,173212647,JoeMokolobetsi,Yeshua Hamashiach is THE answer | Romans 10:9-...,Afrika Borwa,219,197,4789,2010-07-31 19:09:22.000000,1560416252937617411,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 08:07:26.836769
1,1,335041409,XclusivasPuebla,Somos el periódico #ExclusivasPuebla| Investi...,"Puebla, México",1419,6402,70267,2011-07-14 02:02:24.000000,1560416256179707904,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 07:51:50.523048
2,2,1512400441103032323,ShelterAnimalUA,Shelter for abandoned dogs and cats. 1400 dogs...,Ukraine,782,109,1198,2022-04-08 12:02:47.000000,1560416257752666113,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 05:12:06.194216
3,3,1356632630662430722,DogandCatHelpe1,Shelter for abandoned dogs and cats. 1400 dogs...,Ukraine,5,39,690,2021-02-02 15:57:12.000000,1560416257790382081,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 11:22:26.824532
4,4,20297125,ElMananaOnline,Las mejores noticias de los dos Laredos y el m...,Nuevo Laredo,2269,17978,56188,2009-02-07 06:32:49.000000,1560416257937051648,...,0,NaN,0,0,NaN,False,0,0,NaN,2022-08-19 11:52:29.448634

In [6]:
#drop columns
data_df = data.drop(['original_tweet_userid', 'acctdesc', 'location', 'coordinates', 'original_tweet_username', 'in_reply_to_status_id', 'in_reply_to_user_id','in_reply_to_screen_name', 'is_quote_status', 'quoted_status_id', 'quoted_status_userid',
       'quoted_status_username'], axis=1)

In [7]:
data_df

,Unnamed: 0,userid,username,following,followers,totaltweets,usercreatedts,tweetid,tweetcreatedts,retweetcount,text,hashtags,language,favorite_count,is_retweet,original_tweet_id,extractedts
0,0,173212647,JoeMokolobetsi,219,197,4789,2010-07-31 19:09:22.000000,1560416252937617411,2022-08-19 00:00:00,0,Dear vaccine advocate\n\nDo take the COVID19 m...,"[{'text': 'Pfizer', 'indices': [189, 196]}, {'...",en,0,False,0,2022-08-19 08:07:26.836769
1,1,335041409,XclusivasPuebla,1419,6402,70267,2011-07-14 02:02:24.000000,1560416256179707904,2022-08-19 00:00:01,0,#Mundo \n\nAl menos 6 muertos y 16 heridos en ...,"[{'text': 'Mundo', 'indices': [0, 6]}, {'text'...",es,0,False,0,2022-08-19 07:51:50.523048
2,2,1512400441103032323,ShelterAnimalUA,782,109,1198,2022-04-08 12:02:47.000000,1560416257752666113,2022-08-19 00:00:01,0,"Animal shelter Dogs and Cats, we need your hel...","[{'text': 'Ukraine', 'indices': [189, 197]}, {...",en,1,False,0,2022-08-19 05:12:06.194216
3,3,1356632630662430722,DogandCatHelpe1,5,39,690,2021-02-02 15:57:12.000000,1560416257790382081,2022-08-19 00:00:01,0,"Welcome to our shelter!\nLocated in Ukraine, K...","[{'text': 'Ukraine', 'indices': [194, 202]}, {...",en,2,False,0,2022-08-19 11:22:26.824532
4,4,20297125,ElMananaOnline,2269,17978,56188,2009-02-07 06:32:49.000000,1560416257937051648,2022-08-19 00:00:01,0,"Tensión, debido a que #Rusia sigue en pie en l...","[{'text': 'Rusia', 'indices': [22, 28]}, {'tex...",es,0,False,0,2022-08-19 11:52:29.448634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47989,47989,1553460900727853056,Ksana_tt_,237,157,51,2022-07-30 19:22:33.000000,1560778594703577090,2022-08-19 23:59:49,2,"Everything as usual, just another russian gove...","[{'text': 'RussiaIsATerroristState', 'indices'...",en,4,False,0,2022-08-20 01:34:19.026497
47990,47990,132907794,krishtopa,687,488,23608,2010-04-14 14:01:46.000000,1560778614169288705,2022-08-19 23:59:54,0,@dosnostalgic twisted firestarter!,[],en,2,False,0,2022-08-20 01:33:03.111239
47991,47991,14445094,El_Ciudadano,71965,553230,226276,2008-04-19 17:43:02.000000,1560778618208342016,2022-08-19 23:59:55,0,La ruleta Ep. 7: #Ucrania: Presidente Zelensky...,"[{'text': 'Ucrania', 'indices': [17, 25]}]",es,0,False,0,2022-08-20 00:52:50.050159
47992,47992,1382090090059534336,ElCiudadano_Mx,461,1109,30631,2021-04-13 21:57:41.000000,1560778619428999168,2022-08-19 23:59:55,0,La ruleta Ep. 7: #Ucrania: Presidente Zelensky...,"[{'text': 'Ucrania', 'indices': [17, 25]}]",es,0,False,0,2022-08-20 00:52:50.040182
47993,47993,243266116,TheBrianHopkins,1423,3325,1904,2011-01-26 17:36:18.000000,1560778628056637441,2022-08-19 23:59:57,3,When people say the US was in better shape whi...,"[{'text': 'Biden', 'indices': [151, 157]}, {'t...",en,12,False,0,2022-08-20 00:37:50.546178

In [8]:
#add new column called Popularity
bin_label = ['No Popularity','Low Popularity','Medium Populatrity','High Popularity']
bin_cut = [-1,0,150,300,1000]
data_df['Popularity'] = pd.cut(data_df['retweetcount'],bins=bin_cut,labels=bin_label)
data_df.head()

,Unnamed: 0,userid,username,following,followers,totaltweets,usercreatedts,tweetid,tweetcreatedts,retweetcount,text,hashtags,language,favorite_count,is_retweet,original_tweet_id,extractedts,Popularity
0,0,173212647,JoeMokolobetsi,219,197,4789,2010-07-31 19:09:22.000000,1560416252937617411,2022-08-19 00:00:00,0,Dear vaccine advocate\n\nDo take the COVID19 m...,"[{'text': 'Pfizer', 'indices': [189, 196]}, {'...",en,0,False,0,2022-08-19 08:07:26.836769,No Popularity
1,1,335041409,XclusivasPuebla,1419,6402,70267,2011-07-14 02:02:24.000000,1560416256179707904,2022-08-19 00:00:01,0,#Mundo \n\nAl menos 6 muertos y 16 heridos en ...,"[{'text': 'Mundo', 'indices': [0, 6]}, {'text'...",es,0,False,0,2022-08-19 07:51:50.523048,No Popularity
2,2,1512400441103032323,ShelterAnimalUA,782,109,1198,2022-04-08 12:02:47.000000,1560416257752666113,2022-08-19 00:00:01,0,"Animal shelter Dogs and Cats, we need your hel...","[{'text': 'Ukraine', 'indices': [189, 197]}, {...",en,1,False,0,2022-08-19 05:12:06.194216,No Popularity
3,3,1356632630662430722,DogandCatHelpe1,5,39,690,2021-02-02 15:57:12.000000,1560416257790382081,2022-08-19 00:00:01,0,"Welcome to our shelter!\nLocated in Ukraine, K...","[{'text': 'Ukraine', 'indices': [194, 202]}, {...",en,2,False,0,2022-08-19 11:22:26.824532,No Popularity
4,4,20297125,ElMananaOnline,2269,17978,56188,2009-02-07 06:32:49.000000,1560416257937051648,2022-08-19 00:00:01,0,"Tensión, debido a que #Rusia sigue en pie en l...","[{'text': 'Rusia', 'indices': [22, 28]}, {'tex...",es,0,False,0,2022-08-19 11:52:29.448634,No Popularity

In [9]:
polarity_scores = []
for text in data_df["text"]:
    score = sent_analyzer.polarity_scores(text)["compound"]
    polarity_scores.append(score)
data_df["polarity_score"] = polarity_scores

In [10]:
def format_output(output_1):
    polarity = "neutral"
    
    if(output_1['compound']>=.05):
        polarity = "positive"
    elif(output_1['compound']<=-.05):
        polarity = "negative"
    return polarity
def predict_1(text):
    output_dict = sent_analyzer.polarity_scores(text)
    return format_output(output_dict)

data_df['sentiment_category'] = data_df['text'].apply(predict_1)

In [11]:
sentiments = []
for i in range(len(data_df)):
    text = data_df.iloc[i]["text"]
    scores = sent_analyzer.polarity_scores(text)
    max_score = max(scores, key=scores.get)
    if max_score == "pos":
        sentiments.append("positive")
    elif max_score == "neg":
        sentiments.append("negative")
    else:
        sentiments.append("neutral")
data_df["dominant_sentiment"] = sentiments

In [12]:
data_df.rename(columns={'polarity_score':'compound'})

,Unnamed: 0,userid,username,following,followers,totaltweets,usercreatedts,tweetid,tweetcreatedts,retweetcount,...,hashtags,language,favorite_count,is_retweet,original_tweet_id,extractedts,Popularity,compound,sentiment_category,dominant_sentiment
0,0,173212647,JoeMokolobetsi,219,197,4789,2010-07-31 19:09:22.000000,1560416252937617411,2022-08-19 00:00:00,0,...,"[{'text': 'Pfizer', 'indices': [189, 196]}, {'...",en,0,False,0,2022-08-19 08:07:26.836769,No Popularity,-0.6757,negative,neutral
1,1,335041409,XclusivasPuebla,1419,6402,70267,2011-07-14 02:02:24.000000,1560416256179707904,2022-08-19 00:00:01,0,...,"[{'text': 'Mundo', 'indices': [0, 6]}, {'text'...",es,0,False,0,2022-08-19 07:51:50.523048,No Popularity,0.0000,neutral,neutral
2,2,1512400441103032323,ShelterAnimalUA,782,109,1198,2022-04-08 12:02:47.000000,1560416257752666113,2022-08-19 00:00:01,0,...,"[{'text': 'Ukraine', 'indices': [189, 197]}, {...",en,1,False,0,2022-08-19 05:12:06.194216,No Popularity,0.4574,positive,neutral
3,3,1356632630662430722,DogandCatHelpe1,5,39,690,2021-02-02 15:57:12.000000,1560416257790382081,2022-08-19 00:00:01,0,...,"[{'text': 'Ukraine', 'indices': [194, 202]}, {...",en,2,False,0,2022-08-19 11:22:26.824532,No Popularity,0.7418,positive,neutral
4,4,20297125,ElMananaOnline,2269,17978,56188,2009-02-07 06:32:49.000000,1560416257937051648,2022-08-19 00:00:01,0,...,"[{'text': 'Rusia', 'indices': [22, 28]}, {'tex...",es,0,False,0,2022-08-19 11:52:29.448634,No Popularity,0.0000,neutral,neutral
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47989,47989,1553460900727853056,Ksana_tt_,237,157,51,2022-07-30 19:22:33.000000,1560778594703577090,2022-08-19 23:59:49,2,...,"[{'text': 'RussiaIsATerroristState', 'indices'...",en,4,False,0,2022-08-20 01:34:19.026497,Low Popularity,0.4215,positive,neutral
47990,47990,132907794,krishtopa,687,488,23608,2010-04-14 14:01:46.000000,1560778614169288705,2022-08-19 23:59:54,0,...,[],en,2,False,0,2022-08-20 01:33:03.111239,No Popularity,0.0000,neutral,neutral
47991,47991,14445094,El_Ciudadano,71965,553230,226276,2008-04-19 17:43:02.000000,1560778618208342016,2022-08-19 23:59:55,0,...,"[{'text': 'Ucrania', 'indices': [17, 25]}]",es,0,False,0,2022-08-20 00:52:50.050159,No Popularity,0.0000,neutral,neutral
47992,47992,1382090090059534336,ElCiudadano_Mx,461,1109,30631,2021-04-13 21:57:41.000000,1560778619428999168,2022-08-19 23:59:55,0,...,"[{'text': 'Ucrania', 'indices': [17, 25]}]",es,0,False,0,2022-08-20 00:52:50.040182,No Popularity,0.0000,neutral,neutral
47993,47993,243266116,TheBrianHopkins,1423,3325,1904,2011-01-26 17:36:18.000000,1560778628056637441,2022-08-19 23:59:57,3,...,"[{'text': 'Biden', 'indices': [151, 157]}, {'t...",en,12,False,0,2022-08-20 00:37:50.546178,Low Popularity,0.4926,positive,neutral

In [13]:
#using compound score
data_df[['sentiment_category','Popularity']].value_counts()

sentiment_category  Popularity
neutral             No Popularity         21310
negative            No Popularity          8931
positive            No Popularity          7067
neutral             Low Popularity         5109
negative            Low Popularity         3137
positive            Low Popularity         2394
negative            Medium Populatrity       15
positive            Medium Populatrity       10
neutral             High Popularity           9
                    Medium Populatrity        6
positive            High Popularity           4
negative            High Popularity           2
dtype: int64

In [14]:
#max value of polarity (positive, negative and neutral)
data_df[['dominant_sentiment','Popularity']].value_counts()

dominant_sentiment  Popularity
neutral             No Popularity         37164
                    Low Popularity        10621
negative            No Popularity            91
positive            No Popularity            53
neutral             Medium Populatrity       31
negative            Low Popularity           17
neutral             High Popularity          15
positive            Low Popularity            2
dtype: int64

In [15]:
accuracy = accuracy_score(data_df['dominant_sentiment'], data_df['sentiment_category'])

print("Accuracy: {}\n".format(accuracy))

# Show the classification report
print(classification_report(data_df['dominant_sentiment'], data_df['sentiment_category']))

Accuracy: 0.5541317664708089

              precision    recall  f1-score   support

    negative       0.01      0.99      0.02       108
     neutral       1.00      0.55      0.71     47831
    positive       0.01      1.00      0.01        55

    accuracy                           0.55     47994
   macro avg       0.34      0.85      0.25     47994
weighted avg       1.00      0.55      0.71     47994